
DECLARE
  WVDD VENDEDOR%ROWTYPE;
  CURSOR CVDD IS
    SELECT CD_VDD,NM_VDD,VL_SAL,CD_SUPERVISOR
    FROM VENDEDOR
    ORDER BY VL_SAL DESC;
BEGIN
  OPEN CVDD;
  FETCH CVDD INTO WVDD;
  WHILE CVDD%FOUND LOOP  
    DBMS_OUTPUT.PUT_LINE('VENDEDOR= '||WVDD.NM_VDD||
      ' SALARIO= '||WVDD.VL_SAL);
          FETCH CVDD INTO WVDD;
      END LOOP;
      DBMS_OUTPUT.PUT_LINE('LISTADOS '||CVDD%ROWCOUNT||
      ' VENDEDORES');
  CLOSE CVDD;
  END;
