DECLARE

CURSOR CURSOR_VENDEDOR IS
  SELECT CD_VDD, NM_VDD, VL_SAL
  FROM VENDEDOR;
  
CURSOR CURSOR_VENDAS_VENDEDOR(v_cod_vendedor INT) IS
  SELECT COUNT(*)
  FROM VENDA
  WHERE CD_VDD = v_cod_vendedor AND DT_VEN BETWEEN '01/01/2005' AND '31/12/2005';
  
  LINHAS CURSOR_VENDEDOR%ROWTYPE;
  LINHAS_VENDAS CURSOR_VENDAS_VENDEDOR%ROWTYPE;

  QUANT_VENDAS INT(11);

BEGIN

  FOR LINHAS IN CURSOR_VENDEDOR LOOP
  
  
  DBMS_OUTPUT.PUT_LINE('NOME DO VENDEDOR: ' || LINHAS.NM_VDD);
  DBMS_OUTPUT.PUT_LINE('VALOR DO SALÁRIO R$ ' || LINHAS.VL_SAL);
  
  IF LINHAS.VL_SAL > 500 THEN
  
    -- ABRE CURSOR DE VENDAS DO VENDEDOR
    OPEN CURSOR_VENDAS_VENDEDOR(LINHAS.CD_VDD);
      
        FETCH CURSOR_VENDAS_VENDEDOR INTO QUANT_VENDAS;
        DBMS_OUTPUT.PUT_LINE('VENDAS EM 2005: ' || QUANT_VENDAS);
        
        EXIT WHEN CURSOR_VENDAS_VENDEDOR%NOTFOUND;
      
    CLOSE CURSOR_VENDAS_VENDEDOR;
    -- FECHA CURSOR DE VENDAS DO VENDEDOR
  
  END IF;
  
  DBMS_OUTPUT.PUT_LINE('');
  
  END LOOP;

  

END;