DECLARE

CURSOR CURSOR_VENDEDOR IS
  SELECT NM_VDD, VL_SAL
  FROM VENDEDOR;
  
  LINHAS CURSOR_VENDEDOR%ROWTYPE;

BEGIN

  FOR LINHAS IN CURSOR_VENDEDOR LOOP
  
  DBMS_OUTPUT.PUT_LINE('NOME DO VENDEDOR: ' || LINHAS.NM_VDD);
  DBMS_OUTPUT.PUT_LINE('VALOR DO SALÁRIO R$ ' || LINHAS.VL_SAL);
  DBMS_OUTPUT.PUT_LINE('');
  
  END LOOP;

END;