DECLARE

CURSOR CURSOR_CLIENTES IS
  SELECT NM_CLI, NM_CID
  FROM CLIENTE
  ORDER BY NM_CLI DESC;

LINHAS CURSOR_CLIENTES%ROWTYPE;

CONTA INT(11);

BEGIN

CONTA := 0;

  FOR LINHAS IN CURSOR_CLIENTES LOOP
        
    DBMS_OUTPUT.PUT_LINE('NOME DO CLIENTE: ' || LINHAS.NM_CLI);
    DBMS_OUTPUT.PUT_LINE('CIDADE: ' || LINHAS.NM_CID);
    DBMS_OUTPUT.PUT_LINE('');
    
    CONTA := CONTA + 1;
    
  END LOOP;

DBMS_OUTPUT.PUT_LINE('QUANT. CLIENTES ' || CONTA);

END;