DECLARE

CURSOR CURSOR_CLIENTES IS
  SELECT NM_CLI, NM_CID
  FROM CLIENTE;

LINHAS CURSOR_CLIENTES%ROWTYPE;

BEGIN

  FOR LINHAS IN CURSOR_CLIENTES LOOP
  
    DBMS_OUTPUT.PUT_LINE('NOME DO CLIENTE: ' || LINHAS.NM_CLI);
    DBMS_OUTPUT.PUT_LINE('CIDADE: ' || LINHAS.NM_CID);
    DBMS_OUTPUT.PUT_LINE('');
  
  END LOOP;

END;