
DECLARE
 WNM_VDD VENDEDOR.NM_VDD%TYPE;
 WVL_SAL VENDEDOR.VL_SAL%TYPE;
 WNM_CLI CLIENTE.NM_CLI%TYPE;
 RVDD VENDEDOR%ROWTYPE;
 WNR_VDD NUMBER(5);
 I NUMBER(5);
BEGIN
  I:= 1;
  BEGIN
   SELECT COUNT(*) INTO WNR_VDD FROM VENDEDOR;
     WHILE I<= WNR_VDD LOOP
--   LOOP
--   FOR I IN 1..WNR_VDD LOOP
     SELECT * INTO RVDD FROM VENDEDOR WHERE CD_VDD=I;
     DBMS_OUTPUT.PUT_LINE('NOME=  '||RVDD.NM_VDD||' SALARIO= '||RVDD.VL_SAL);
     IF RVDD.VL_SAL < 1000 THEN
       DBMS_OUTPUT.PUT_LINE('SALÁRIO BAIXO!');
     ELSIF RVDD.VL_SAL>100 AND RVDD.VL_SAL < 2000 THEN
       DBMS_OUTPUT.PUT_LINE('SALÁRIO MÉDIO!');
     ELSE
       DBMS_OUTPUT.PUT_LINE('SALÁRIO ALTO!');
     END IF;
     I:=I + 1;
     EXIT WHEN I> WNR_VDD;
   END LOOP;
   EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('VENDEDOR INEXISTENTE');
  END;
  BEGIN
   SELECT NM_CLI INTO WNM_CLI FROM CLIENTE WHERE CD_CLI>1;
   DBMS_OUTPUT.PUT_LINE('CLIENTE=  '||WNM_CLI);
  EXCEPTION
   WHEN TOO_MANY_ROWS THEN
     DBMS_OUTPUT.PUT_LINE('MUITOS CLIENTES RETORNADOS');
  END;
  DBMS_OUTPUT.PUT_LINE('FIM DE EXECUÇÃO');
  SELECT NM_CLI INTO WNM_CLI FROM CLIENTE WHERE CD_CLI=200;
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('ERRO!! COTATE O ADMINISTRADOR DO SISTEMA');
  END;
  