DECLARE
  CURSOR CCLI IS
    SELECT CD_CLI,NM_CLI,NM_CID FROM CLIENTE ORDER BY NM_CID DESC;
  RCLI CCLI%ROWTYPE;
  CURSOR CVEN(PCOD_CLI NUMBER) IS
    SELECT CD_LOJ,CD_VEN,DT_VEN FROM VENDA
       WHERE CD_CLI = PCOD_CLI;
  RVEN CVEN%ROWTYPE;
BEGIN
  OPEN CCLI;
  FETCH CCLI INTO RCLI;
  WHILE CCLI%FOUND LOOP
	DBMS_OUTPUT.PUT_LINE('CLIENTE= '||RCLI.NM_CLI||' CIDADE= '||RCLI.NM_CID);
    FETCH CCLI INTO RCLI;
    OPEN CVEN(RCLI.CD_CLI);
    FETCH CVEN INTO RVEN;
    WHILE CVEN%FOUND LOOP
      DBMS_OUTPUT.PUT_LINE('.     LOJA= '||RVEN.CD_LOJ||
        ' VENDA= '||RVEN.CD_VEN||
        ' DATA= '||RVEN.DT_VEN);
      FETCH CVEN INTO RVEN;
    END LOOP;
    CLOSE CVEN;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE(CCLI%ROWCOUNT);
  CLOSE CCLI;
END;
