-- RETORNAR O NOME E O SALARIO DO VENDEDOR 3
DECLARE
  WNM_VDD VENDEDOR.NM_VDD%TYPE;
  WVL_SAL VENDEDOR.VL_SAL%TYPE;
  WNR_VDD NUMBER(3);
  CONT NUMBER(3);
BEGIN
  CONT := 1;
--  SELECT COUNT(*) INTO WNR_VDD FROM VENDEDOR;
  SELECT MAX(CD_VDD) INTO WNR_VDD FROM VENDEDOR;
--  FOR CONT IN 1..WNR_VDD LOOP
--  WHILE CONT <= WNR_VDD LOOP
  LOOP
    BEGIN
      SELECT NM_VDD,VL_SAL INTO WNM_VDD,WVL_SAL 
      FROM VENDEDOR WHERE CD_VDD= CONT;
      IF WVL_SAL < 1000 THEN
        DBMS_OUTPUT.PUT_LINE('VENDEDOR= '||WNM_VDD||
  								  		' SALARIO= '||WVL_SAL||' SALARIO BAIXO!!');
      ELSIF WVL_SAL > 1000 AND WVL_SAL < 3000 THEN
        DBMS_OUTPUT.PUT_LINE('VENDEDOR= '||WNM_VDD||
  								  		' SALARIO= '||WVL_SAL||' SALARIO MÉDIO!!');
      ELSE
	    DBMS_OUTPUT.PUT_LINE('VENDEDOR= '||WNM_VDD||
  								  		' SALARIO= '||WVL_SAL||' SALARIO ALTO!!');
      END IF;
    EXCEPTION
	  WHEN NO_DATA_FOUND THEN
	    DBMS_OUTPUT.PUT_LINE('VENDEDOR = '||CONT||
	  								 ' NÃO EXISTE!!');
	END;
    CONT := CONT + 1;
    EXIT WHEN CONT > WNR_VDD;
    END LOOP;
END;

