DECLARE

CODIGO_PARCELA PARCELA.CD_PAR%TYPE;
VENCIMENTO_PARCELA PARCELA.DT_VCTO%TYPE;
VALOR_PARCELA PARCELA.VL_PAR%TYPE;
X INTEGER(11);

BEGIN

X := 1;
WHILE X <= 5 LOOP

  SELECT P.CD_PAR, P.DT_VCTO, P.VL_PAR INTO CODIGO_PARCELA, VENCIMENTO_PARCELA, VALOR_PARCELA
  FROM PARCELA P
  WHERE P.CD_LOJ = 1 AND P.CD_VEN = 1 AND P.CD_PAR = X;
  
  DBMS_OUTPUT.put_line('CODIGO DA PARCELA: ' || CODIGO_PARCELA || ' - VENCTO: ' || VENCIMENTO_PARCELA || ' - VALOR R$: ' || VALOR_PARCELA);
  
  X := X + 1;
  
END LOOP;

END;