DECLARE

NOME_VENDEDOR VENDEDOR.NM_VDD%TYPE;
SUPERVISOR_VENDEDOR VENDEDOR.CD_SUPERVISOR%TYPE;
SALARIO FLOAT(5);


W_NOME_VENDEDOR VENDEDOR.NM_VDD%TYPE;
W_SUPERVISOR_VENDEDOR VENDEDOR.CD_VDD%TYPE;

BEGIN

SELECT NM_VDD, CD_SUPERVISOR, VL_SAL INTO NOME_VENDEDOR, SUPERVISOR_VENDEDOR, SALARIO
FROM VENDEDOR
WHERE CD_VDD = 3;

DBMS_OUTPUT.PUT_LINE('NOME DO VENDEDOR ' || NOME_VENDEDOR 
                    || ' SALARIO: ' || SALARIO
                    || ' SUPERVISOR: ' || SUPERVISOR_VENDEDOR);


IF SALARIO > 1000 THEN

  SELECT NM_VDD, CD_VDD INTO W_NOME_VENDEDOR, W_SUPERVISOR_VENDEDOR
  FROM VENDEDOR
  WHERE CD_VDD = SUPERVISOR_VENDEDOR;
  
  DBMS_OUTPUT.put_line(' NOME DO SUPERVISOR: ' || W_NOME_VENDEDOR || ' - CÓD DELE: ' || W_SUPERVISOR_VENDEDOR);

END IF;

END;