DECLARE

NOME_CLIENTE CLIENTE.NM_CLI%TYPE;
VALOR_TOTAL FLOAT(5);
QUANT_PARCELAS INT(11);

BEGIN

FOR WLOJ IN 1..3 LOOP
  FOR WVEN IN 1..5 LOOP

    SELECT C.NM_CLI, SUM(VL_PAR) INTO NOME_CLIENTE, VALOR_TOTAL
    FROM CLIENTE C, PARCELA P, VENDA V
    WHERE V.CD_VEN = P.CD_VEN
      AND C.CD_CLI = V.CD_CLI
      AND V.CD_LOJ = WLOJ
      AND V.CD_VEN = WVEN
    GROUP BY C.NM_CLI;

    SELECT COUNT(*) INTO QUANT_PARCELAS
    FROM PARCELA PP
    WHERE PP.CD_LOJ = WLOJ 
      AND PP.CD_VEN = WVEN
      AND PP.DT_VCTO < SYSDATE AND PP.VL_PAGO IS NULL;
      
    DBMS_OUTPUT.PUT_LINE('NOME DO CLIENTE: ' || NOME_CLIENTE || ' - VALOR TOTAL: R$ ' || VALOR_TOTAL);
  
    IF QUANT_PARCELAS > 0 THEN
      DBMS_OUTPUT.PUT_LINE('SITUAÇÃO DEVEDORA');
      DBMS_OUTPUT.PUT_LINE('');
    ELSE
      
      DBMS_OUTPUT.PUT_LINE('SITUAÇÃO NORMAL');
      DBMS_OUTPUT.PUT_LINE('');
    END IF;

  END LOOP;
END LOOP;

END;