-- QUESTÃO 01

DECLARE

  NOME_VENDEDOR VENDEDOR.NM_VDD%TYPE;
  SUPERVISOR_VENDEDOR VENDEDOR.CD_SUPERVISOR%TYPE;
  SALARIO FLOAT(5);


  W_NOME_VENDEDOR VENDEDOR.NM_VDD%TYPE;
  W_SUPERVISOR_VENDEDOR VENDEDOR.CD_VDD%TYPE;

BEGIN

  SELECT NM_VDD, CD_SUPERVISOR, VL_SAL INTO NOME_VENDEDOR, SUPERVISOR_VENDEDOR, SALARIO
  FROM VENDEDOR
  WHERE CD_VDD = 3;

  DBMS_OUTPUT.PUT_LINE('NOME DO VENDEDOR ' || NOME_VENDEDOR 
                      || ' SALARIO: ' || SALARIO
                      || ' SUPERVISOR: ' || SUPERVISOR_VENDEDOR);


  IF SALARIO > 1000 THEN

    SELECT NM_VDD, CD_VDD INTO W_NOME_VENDEDOR, W_SUPERVISOR_VENDEDOR
    FROM VENDEDOR
    WHERE CD_VDD = SUPERVISOR_VENDEDOR;
    
    DBMS_OUTPUT.put_line(' NOME DO SUPERVISOR: ' || W_NOME_VENDEDOR || ' - CÓD DELE: ' || W_SUPERVISOR_VENDEDOR);

  END IF;

END;


-- QUESTÃO 2

DECLARE

  NOME_VENDEDOR VENDEDOR.NM_VDD%TYPE;
  QUANTIDADE_VENDIDA FLOAT(5);
  SOMA_PARCELAS PARCELA.VL_PAR%TYPE;

BEGIN

  SELECT VDD.NM_VDD, SUM(QT_VEN) INTO NOME_VENDEDOR, QUANTIDADE_VENDIDA
  FROM VENDEDOR VDD, VENDA V, ITEM_VENDA IV
  WHERE V.CD_VEN = 3 
    AND V.CD_LOJ = 1
    AND V.CD_VEN = IV.CD_VEN
    AND VDD.CD_VDD = V.CD_VDD
    GROUP BY VDD.NM_VDD;

  DBMS_OUTPUT.put_line('Nome do vendedor: ' || NOME_VENDEDOR || 
                      ' - Qtde. vendida: ' || QUANTIDADE_VENDIDA);

  IF QUANTIDADE_VENDIDA > 3 THEN

  SELECT SUM(VL_PAR) INTO SOMA_PARCELAS
  FROM PARCELA P
  WHERE P.CD_VEN = 3 AND P.CD_LOJ = 1;

  DBMS_OUTPUT.put_line('Valor total R$: ' || SOMA_PARCELAS);

  END IF;

END;


-- QUESTÃO 03

DECLARE

  CODIGO_PARCELA PARCELA.CD_PAR%TYPE;
  VENCIMENTO_PARCELA PARCELA.DT_VCTO%TYPE;
  VALOR_PARCELA PARCELA.VL_PAR%TYPE;
  X INTEGER(11);

BEGIN

  X := 1;
  WHILE X <= 5 LOOP

    SELECT P.CD_PAR, P.DT_VCTO, P.VL_PAR INTO CODIGO_PARCELA, VENCIMENTO_PARCELA, VALOR_PARCELA
    FROM PARCELA P
    WHERE P.CD_LOJ = 1 AND P.CD_VEN = 1 AND P.CD_PAR = X;
    
    DBMS_OUTPUT.put_line('CODIGO DA PARCELA: ' || CODIGO_PARCELA || ' - VENCTO: ' || VENCIMENTO_PARCELA || ' - VALOR R$: ' || VALOR_PARCELA);
    
    X := X + 1;
    
  END LOOP;

END;


-- QUESTÃO 05

DECLARE

  NOME_CLIENTE CLIENTE.NM_CLI%TYPE;
  VALOR_TOTAL FLOAT(5);
  QUANT_PARCELAS INT(11);

BEGIN

  FOR WLOJ IN 1..3 LOOP
    FOR WVEN IN 1..5 LOOP

      SELECT C.NM_CLI, SUM(VL_PAR) INTO NOME_CLIENTE, VALOR_TOTAL
      FROM CLIENTE C, PARCELA P, VENDA V
      WHERE V.CD_VEN = P.CD_VEN
        AND C.CD_CLI = V.CD_CLI
        AND V.CD_LOJ = WLOJ
        AND V.CD_VEN = WVEN
      GROUP BY C.NM_CLI;

      SELECT COUNT(*) INTO QUANT_PARCELAS
      FROM PARCELA PP
      WHERE PP.CD_LOJ = WLOJ 
        AND PP.CD_VEN = WVEN
        AND PP.DT_VCTO < SYSDATE AND PP.VL_PAGO IS NULL;
        
      DBMS_OUTPUT.PUT_LINE('NOME DO CLIENTE: ' || NOME_CLIENTE || ' - VALOR TOTAL: R$ ' || VALOR_TOTAL);
    
      IF QUANT_PARCELAS > 0 THEN
        DBMS_OUTPUT.PUT_LINE('SITUAÇÃO DEVEDORA');
        DBMS_OUTPUT.PUT_LINE('');
      ELSE
        
        DBMS_OUTPUT.PUT_LINE('SITUAÇÃO NORMAL');
        DBMS_OUTPUT.PUT_LINE('');
      END IF;

    END LOOP;
  END LOOP;

END;