DECLARE

CURSOR CURSOR_LOJAS IS
  SELECT * FROM LOJA;
  

CURSOR CURSOR_VENDAS(V_CD_VEN INT) IS
  SELECT CD_VEN, DT_VEN
  FROM VENDA;


CURSOR CURSOR_PARCELAS(V_COD_VENDA INT) IS
  SELECT COUNT(*)
  FROM PARCELA
  WHERE DT_PAGTO < SYSDATE AND VL_PAGO IS NULL;

LISTA_LOJAS CURSOR_LOJAS%ROWTYPE;
LISTA_VENDAS CURSOR_VENDAS%ROWTYPE;
LISTA_PARCELAS CURSOR_PARCELAS%ROWTYPE;

BEGIN




END;